name: SonarQube Analysis for MissieMoustass

on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    name: Build and analyze MissieMoustass
    runs-on: ubuntu-latest  # Utilisation d'Ubuntu pour compatibilité Java

    steps:
      - name: Checkout du code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Désactiver les clones peu profonds pour SonarCloud

      - name: Configuration de Java 17
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: 'zulu'  # OpenJDK via Azul (recommandé)

      - name: Vérification de Java
        run: java -version

      - name: Compilation du projet Java (Sans Maven)
        run: |
          mkdir -p bin
          javac -d bin $(find src -name "*.java")

      - name: Installation de SonarScanner
        run: |
          sudo apt update
          sudo apt install -y unzip
          curl -o sonarqube.zip https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-5.0.1.3006-linux.zip
          unzip sonarqube.zip
          mv sonar-scanner-5.0.1.3006-linux sonar-scanner
          echo "$PWD/sonar-scanner/bin" >> $GITHUB_PATH

      - name: Analyse SonarQube
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          sonar-scanner \
            -Dsonar.projectKey=MissieMoustass \
            -Dsonar.organization=ton-organisation-sonarcloud \
            -Dsonar.host.url=https://sonarcloud.io \
            -Dsonar.token=${{ secrets.SONAR_TOKEN }} \
            -Dsonar.sources=src \
            -Dsonar.java.binaries=bin
